title: LAG BW
description: Landesarbeitsgemeinschaft Baden-WÃ¼rttemberg
baseurl: "/lagbw"       # <-- set to your repository name when publishing at username.github.io/reponame
url: "https://benutzereinstweidrei.github.io/lagbw"

repository: BenutzerEinsZweiDrei/lagbw

theme: jekyll-theme-cayman
# No need for jekyll-remote-theme plugin with theme:
