# Site settings
title: LAG BW
description: Landesarbeitsgemeinschaft Baden-WÃ¼rttemberg
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://benutzereinstweidrei.github.io/lagbw" # the base hostname & protocol for your site

# GitHub repository information
repository: BenutzerEinsZweiDrei/lagbw

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
