# Site settings
title: LAG BW
description: Landesarbeitsgemeinschaft Baden-WÃ¼rttemberg
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://benutzereinstweidrei.github.io/lagbw" # the base hostname & protocol for your site

# GitHub repository information
repository: BenutzerEinsZweiDrei/lagbw

# Build settings
# theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - about.md
  - contact.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
